development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  # channel_prefix: runescribe_production
  url: redis://redistogo:50120c0fc785ff0b9b91a12b98f9d17e@sole.redistogo.com:10479/
  