development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  # channel_prefix: runescribe_production
  url: redis://:c45d9aef2a4ddf1262cbb6354f04a30891373b76fa8ab101161e8247274a5c12@dokku-redis-redis-runescribe:6379
  